name: Deploy
on:
  push:
    branches:
      - deploy
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deploy
        run: |
          rm .gitignore || true
          npm install
          git commit -am "Deploy Node Modules"
          git push
        env:
          CI: true