name: Deploy
on:
  push:
    branches:    
      - deploy
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Remove .gitignore
        run: rm .gitignore
      - name: Install Node
        run: npm install
